apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
replicas:
- name: hello-world
  count: 1
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: hello-world
    patch: |-
      - op: replace
        path: /metadata/name
        value: hello-friend-$ARGOCD_APP_REVISION