apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: nginx-custom=registry-service.docker-registry.svc.cluster.local:5000/nginx-custom
    argocd-image-updater.argoproj.io/nginx-custom.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default
  source:
    repoURL: 'ssh://git@github.com/valves-ops/argocd-testing.git'
    path: hello-world/manifests
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: hello-world
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
